### ISSUE TITLE
Could NOT find Armadillo

### ISSUE THREAD

**Issue by zihui1987** [HKUST-Aerial-Robotics/Teach-Repeat-Replan#10]
CMake Error at /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find Armadillo (missing: ARMADILLO_LIBRARY ARMADILLO_INCLUDE_DIR)
Call Stack (most recent call first):

**Comment by USTfgaoaa** [comment]
Seemed you didn't properly install armadillo as stated in README.

Please:  sudo apt-get install libarmadillo-dev

Done.

**Comment by USTfgaoaa** [comment]
@zihui1987

**Comment by zihui1987** [comment]
@USTfgaoaa This method solved my problem. Thanks!
