### ISSUE TITLE
some problem about teaching_planning.sh

### ISSUE THREAD

**Issue by M1nHuan** [HKUST-Aerial-Robotics/Teach-Repeat-Replan#12]
请问在地面站使用teaching_planning.sh的时候需要保持地面站与机载电脑的连接吗？
我们出现的问题是，在保持地面站与机载电脑连接的状态下，运行teaching_planning.sh，会无法加载出model.pcd 并且rviz会异常关闭

**Comment by USTfgaoaa** [comment]
@M1nHuan 链接应该跟你的问题没关系。你确定你的model.pcd这个文件在那儿了吗，文件里的内容正常吗，用别的点云模型软件打开看一下？

**Comment by M1nHuan** [comment]
model.pcd在相应的路径下，如果断开地面站和机载电脑的连接就可以在地面站运行teaching_planning.sh加载出来。
那么是否可以断开地面站和机载电脑的连接再去teaching？
非常感谢您的回复

**Comment by USTfgaoaa** [comment]
@M1nHuan 这个和是否连接应该没有关系。当两个电脑连接时，你的ros master设置正确吗

**Comment by M1nHuan** [comment]
我们将ros master 改为了地面站，然后解决了这个问题
谢谢！
