### ISSUE TITLE
hardware configuration

### ISSUE THREAD

**Issue by gongshichina** [HKUST-Aerial-Robotics/Teach-Repeat-Replan#15]
Hi, thanks for your  many wonderful open source works.  

Would you please tell me what hard configurations you used specifically in this work?

 I am planning to conduct some research about autonomous obstacle avoidance, object tracking and other vision tasks on a drone platform and my next step is to buy some hardware devices. I will appreciate it if you can give me a little bit advice.

Many Thanks.

**Comment by USTfgaoaa** [comment]
@gongshichina 
The hardware list is here:
Drone frame: Q250; motor and ESC: DJI snail; propeller: DJI 5048s; battery: tattu4s2300mah; remote controller: DJI lightbridge2; autopilot: DJI N3; onboard computer: DJI manifold2
