### ISSUE TITLE
Question about specific hardware configuration

### ISSUE THREAD

**Issue by tuandle** [HKUST-Aerial-Robotics/Teach-Repeat-Replan#17]
Hi @USTfgaoaa @bigsuperZZZX 
Thank you for open source your pipeline.
I have some questions regarding the hardware configuration to clarify my understanding.

- Q1: **Is there any hardware synchronization between the realsense camera and N3 controller?** My guess is that you don't have the N3 controller triggering the realsense, given that the time offset between imu and cameras are preset pretty high (~ 18 ms). Is this the reason why you set the imu rate at 400 Hz to mitigate the delay effect? Or is it not necessary to have hardware sync as required by VINS?
- Q2: **The images from infra1/image_rect_raw are rectified by default, except streaming in Y16 format** according to [the realsense wiki](https://github.com/IntelRealSense/librealsense/wiki/Projection-in-RealSense-SDK-2.0#d400-series). The realsense configuration has non zero distortion coefficients. So do we need to use Y16 format instead? 
- Q3: **For surfel mapping, there are unused params such as ric00, tic00, etc.,** I checked the mapping parts and saw that these variables are just declared but never used. Maybe they are reserved for some unreleased functions?
-Q4: **The param center_T_imu is not clear**. What is the center frame? Is it an extrinsic from IMU to the center of the drone?

**Comment by tuandle** [comment]
Thanks @USTfgaoaa for your super quick reply!
Regarding question 2, what I want to ask is how you can get non-zero distortion coeff from **rectified images**? Because according to the realsense wiki, if **not** in Y16 format, images from infra1 and infra2 _are rectified_ before streaming to a host.
Like you said, it is not a concern but just for the sake of clarity :)

**Comment by USTfgaoaa** [comment]
@tuandle OK now I see your question. That's because we manually calibrated these cameras with the published rectified images. Actually, you can just use the intrinsic params read from the realsense driver.  Both OK, we have tested.

**Comment by tuandle** [comment]
Ok, I got it! Thanks again!
