### ISSUE TITLE
about N3Ctrl PID Tune

### ISSUE THREAD

**Issue by HandsomeTong66** [HKUST-Aerial-Robotics/Teach-Repeat-Replan#23]
您好，感谢您开源了此项目。
我们已经组装好了飞机，请问在ctrl_param_fpv.yaml文件中，我们除了需要改变mass参数外，还需要关注哪些参数来调节PID使飞机保持悬停状态。

**Comment by USTfgaoaa** [comment]
@HandsomeTong66 All params are tunable. Pay attention to the hover thrust percentage, position and velocity gain.
