### ISSUE TITLE
Manifold 2 Version

### ISSUE THREAD

**Issue by ArlenCHEN** [HKUST-Aerial-Robotics/Teach-Repeat-Replan#25]
@USTfgaoaa 
From the paper, I can see you used Manifold 2C as the onboard computer. However, from the specifics of DJI website, Manifold 2C does not have wifi module. How can you guys deal with the communication between onboard computer with ground station? Thanks!

**Comment by USTfgaoaa** [comment]
@ArlenCHEN We use a USB wifi dongle.

**Comment by ArlenCHEN** [comment]
Thanks!
