### ISSUE TITLE
Hardware Setup

### ISSUE THREAD

**Issue by NitinJSanket** [HKUST-Aerial-Robotics/Teach-Repeat-Replan#26]
Thanks a lot for your code and wonderful. Can you please elaborate on your hardware setup? ESCs and Motors?

Thanks,
Nitin

**Comment by ArlenCHEN** [comment]
The author has posted the hardware configuration in the closed issues.

**Comment by USTfgaoaa** [comment]
@NitinJSanket The hardware list is here:
Drone frame: Q250; motor and ESC: DJI snail; propeller: DJI 5048s; battery: tattu4s2300mah; remote controller: DJI lightbridge2; autopilot: DJI N3; onboard computer: DJI manifold2

**Comment by NitinJSanket** [comment]
Thanks a lot, I'll close this issue :)
