### ISSUE TITLE
Odometry for controller

### ISSUE THREAD

**Issue by ArlenCHEN** [HKUST-Aerial-Robotics/Teach-Repeat-Replan#27]
@USTfgaoaa 
May I ask why do you use `/vins_estimator/imu_propagate`, instead of `/vins_estimator/odometry` as the odometry for the controller? Thanks!

**Comment by USTfgaoaa** [comment]
@ArlenCHEN For a higher feedback rate.

**Comment by ArlenCHEN** [comment]
Thanks! But I am wondering is there any way to change the frequency of `/vins_estimator/odometry` to meet the control feedback rate in VINS_FUSION?

**Comment by USTfgaoaa** [comment]
@ArlenCHEN No way to change that msgs, which is exactly the frequency of the pose estimation of the VIO. It's impossible to boost the frequency of the VIO to 50~100 Hz in an onboard computer.

**Comment by ArlenCHEN** [comment]
Clear now. Thanks for your kind reply!

**Comment by gouyiyong** [comment]
> @ArlenCHEN For a higher feedback rate.
@USTfgaoaa  are they /vins_estimator/odometry and /vins_estimator/imu_propagate much different?no any difference for control performance? and I wanna make sure if  /vins_estimator/imu_propagate is accurate enough for the controller and the whole system.
