### ISSUE TITLE
A minor fix in pluginlib for those using Ubuntu 18.04 and ROS melodic 

### ISSUE THREAD

**Issue by syangav** [HKUST-Aerial-Robotics/Teach-Repeat-Replan#34]
In Ubuntu 18.04 and ROS melodic, the following compilation error will occur (ubuntu 16.04 & ROS kinetic works fine however):
error: expected constructor, destructor, or type conversion before ‘(’ token
 PLUGINLIB_DECLARE_CLASS(router, RouterNode, RouterNode, nodelet::Nodelet);

The solution is to change the line from: 
PLUGINLIB_DECLARE_CLASS(router, RouterNode, RouterNode, nodelet::Nodelet);
to: 
PLUGINLIB_EXPORT_CLASS(RouterNode, nodelet::Nodelet);

Note that this issue is caused by different versions of pluginlib and this similar issue will happen 3 times (CascadeControllerNode, MissionTemplateNode, RouterNode). Just using similar fixes will be fine. 

One can find the references from [1](https://github.com/KumarRobotics/msckf_vio/issues/69), [2](https://github.com/KumarRobotics/msckf_vio/pull/72), [3](https://answers.ros.org/question/323682/imu_filter_madgwick-does-not-compile-properly-on-ubuntu1804-melodic/).

**Comment by bigsuperZZZX** [comment]
Thank you very much for correction. I will post it to _readme.md_, hoping to help more people that use Ubuntu 18.04 and ROS melodic.

**Comment by 958117216** [comment]
太感谢了！！！！！！！！

**Comment by Akashleena** [comment]
Having the same problem in ROS Noetic and Ubuntu 20.04
