### ISSUE TITLE
I encountered a problem while compiling OOQP

### ISSUE THREAD

**Issue by G1246830895** [HKUST-Aerial-Robotics/Teach-Repeat-Replan#35]
I get an error when I execute the sudo make install command.The error is as follows
/usr/bin/install -c -d /usr/local/include/ooqp	
/usr/bin/install -c ./include/*.h /usr/local/include/ooqp
/usr/bin/install -c -d /usr/local/lib
/usr/bin/install -c ./lib/*.a /usr/local/lib
if [ -d doc-src ]; then cd doc-src; fi; make
make[1]: Entering directory '/home/gzh/Teach-Repeat-Replan-experiment/installation/OOQP-master/doc-src'
cd ooqp-userguide; \
pdflatex  ooqp-userguide; \
bibtex ooqp-userguide; \
pdflatex  ooqp-userguide; \
pdflatex  ooqp-userguide
/bin/sh: 2: pdflatex: not found
/bin/sh: 3: bibtex: not found
/bin/sh: 4: pdflatex: not found
/bin/sh: 5: pdflatex: not found
GNUmakefile:42: recipe for target 'ooqp-userguide/ooqp-userguide.pdf' failed
make[1]: *** [ooqp-userguide/ooqp-userguide.pdf] Error 127
make[1]: Leaving directory '/home/gzh/Teach-Repeat-Replan-experiment/installation/OOQP-master/doc-src'
GNUmakefile:102: recipe for target 'install_docs' failed
make: *** [install_docs] Error 2

How can i solve this problem？

**Comment by USTfgaoaa** [comment]
@G1246830895 This error doesn't matter. It's just generating related documents. Your OOQP solver has already been compiled successfully.
