### ISSUE TITLE
Onboard SDK compilation issues

### ISSUE THREAD

**Issue by G1246830895** [HKUST-Aerial-Robotics/Teach-Repeat-Replan#37]
When I copied the code in the "Onboard_computer" folder to the ROS workspace for compilation according to the readme file, the following problems occurred:
CMake Error at onboard_computer/controller/djiros/CMakeLists.txt:36 (find_package):
  By not providing "FindDJIOSDK.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "DJIOSDK", but
  CMake did not find one.

  Could not find a package configuration file provided by "DJIOSDK" with any
  of the following names:

    DJIOSDKConfig.cmake
    djiosdk-config.cmake

  Add the installation prefix of "DJIOSDK" to CMAKE_PREFIX_PATH or set
  "DJIOSDK_DIR" to a directory containing one of the above files.  If
  "DJIOSDK" provides a separate development package or SDK, be sure it has
  been installed.
This problem is very similar to the Cmake problem caused by compiling "joy_ctrl". How should I solve it?

**Comment by bigsuperZZZX** [comment]
Make sure this step is performed correctly.
![image](https://user-images.githubusercontent.com/26641182/86078597-0a26f080-bac1-11ea-8c6e-80953fefada5.png)

**Comment by G1246830895** [comment]
I did this. I followed the "step by step" tutorial for installation. The onboard computer I use is a dji manifold2 g. My Onboard-SDK is installed under "home", djiros I git to the src folder in the ROS workspace. When I compile, the same problem occurs.

**Comment by bigsuperZZZX** [comment]
I have no idea about the solution. Because we compiled djiros successfully on manifold-2C.
Make sure you have properly installed Onboard-SDK via "sudo make install" and can be find from a simple CMakeLists.txt.
Maybe you can try to follow the steps from dji-developer websites to check your installation.
