### ISSUE TITLE
The plugin for class 'rviz_plugins/Goal3DTool' failed to load.

### ISSUE THREAD

**Issue by huangwen0907** [HKUST-Aerial-Robotics/Teach-Repeat-Replan#4]
Hi, Nice project, I love this `Teach-Repeat-Replan`.
Now I followed your advices and install all the files and it can run. 
I run the recent commit ['3c8627322b'](https://github.com/HKUST-Aerial-Robotics/Teach-Repeat-Replan/commit/b0c008ebb5292376ac567963e419263c8627322b) in master branch
But there are some errors which i can not control it.  I am very appreciate that 
 someone can help me .
- 1 The plugin for class 'rviz_plugins/Goal3DTool' failed to load. The errors show as below:
![Screenshot from 2019-07-18 13-52-29](https://user-images.githubusercontent.com/22727672/61432987-add8c880-a964-11e9-80c0-74b48daa8d72.png)

- 2 The [local_replanner-1] process has died, show as below:
![Screenshot from 2019-07-18 13-50-17](https://user-images.githubusercontent.com/22727672/61433054-e082c100-a964-11e9-96a3-13966c6c512a.png)
- 3 The depthImage's status is 'warn', Maybe this one is not a question, Just for your information
![Screenshot from 2019-07-18 13-56-48](https://user-images.githubusercontent.com/22727672/61433101-f8f2db80-a964-11e9-9832-2ca665dabd80.png)

- 4 hhahah, the dirty words.
![Screenshot from 2019-07-18 13-48-40](https://user-images.githubusercontent.com/22727672/61433198-3fe0d100-a965-11e9-947f-b46011f7cce8.png)

I am a new beginner in this project, so forgive the Idiot question

**Comment by ZbyLGsc** [comment]
@huangwen0907 The reason you can not load the Goal3DTool cloud be not sourcing the setup.bash before running the simulation(source setup.bash in the same terminal you launch the simulation). As for the dying of local_replanner, I can not figure out what happened from the single screenshot. More details will help, please.

**Comment by huangwen0907** [comment]
@ZbyLGsc Thank you for your reply, follow your step, I find out that  the reason  of `dying of local_replanner`. As before I use the `zsh` which change my environment, now I switch to the `bash` and the node died do not happen again. 
However, it still load the ` the Goal3DTool cloud ` faild.
![111](https://user-images.githubusercontent.com/22727672/61437454-b387db80-a96f-11e9-8815-42f8d6bcfe5d.png)

- One more question. I can not reply the path when I press the button `M`or (auto) mode when I finish the manual mode(flying a circle without any obstacle). It print the info that `it can not find a safe path`(show as below)
![Screenshot from 2019-07-18 15-22-28](https://user-images.githubusercontent.com/22727672/61437576-0bbedd80-a970-11e9-9624-ca0932c4c784.png)

![Screenshot from 2019-07-18 13-48-40](https://user-images.githubusercontent.com/22727672/61437606-1aa59000-a970-11e9-97e4-934358da0258.png)

**Comment by ZbyLGsc** [comment]
@huangwen0907 You can ignore 1,3,4 safely. As for problem 2, I just try the simulation several times and can not reproduce your result. More details will be helpful.

**Comment by huangwen0907** [comment]
@ZbyLGsc ok, Thank you very much. 
Could you please give me some reply about the `replay` can not be executed when I enter the `auto` mode ?

**Comment by ZbyLGsc** [comment]
@huangwen0907 Congrat! And I already removed the above mentioned plugins, since they are unused in this project.

**Comment by USTfgaoaa** [comment]
Hi bro,

1. The dependencies on rviz plugin has no harm to this program. And boyu has fixed them

2. According to our paper，we find the topo equivalent path of the teaching. So if you fly the drone a circle without go around any obstacle，the topo equivalent path is nothing. So try to teach the drone to fly around obstacles and then go back（just like the demo in our git），and press M again.

**Comment by huangwen0907** [comment]
@USTfgaoaa  Thank you .  All the works is valid now except onething, It can be control in manual mode and a new replay path  can be generated in auto mode. However when I entered the auto mode, the simulation vehicle landed on the ground automatically. So the vehicle did not do the replay work(fly with the generation replay path). This is normal? Show as below:
![new path](https://user-images.githubusercontent.com/22727672/61439237-bb497f00-a973-11e9-9b8d-90d412c359f9.png)

**Comment by huangwen0907** [comment]
@ZbyLGsc  Nice! Good Catch.  If the bug exists, in the real world, when armed the motors, the vehicle may inverted, This is very dangerous.

-  5) it show the error of my licesense.
> Error MSK_RES_ERR_MISSING_LICENSE_FILE - 'A license cannot be located.'
![MSK_RES_ERR_MISSING_LICENSE_FILEs](https://user-images.githubusercontent.com/22727672/61441112-817a7780-a977-11e9-8488-4e2f59c67a63.png)

-6) In my rviz, no depthIMage is showed. could you tell me the topic is published from which node?
![msg](https://user-images.githubusercontent.com/22727672/61441333-fc439280-a977-11e9-9f46-6129583e48e9.png)

**Comment by USTfgaoaa** [comment]
Hi，

1. You should approve a academic license in Mosek website. Follow the instruction in ReadMe.

2. In CPU mode，depth image will not be published. If you want it, turn on GPU mode in the local sensing package. But firstly you should make sure you have installed CUDA properly. Please follow the ReadMe for details.

**Comment by huangwen0907** [comment]
@USTfgaoaa  OK, I will have a try. Thank you.
All my problems is solved now, I will close this issues. If you have any question, please feel free to reopen this.

**Comment by lei0907** [comment]
How did you solve the first problem?The plugin for class 'rviz_plugins/Goal3DTool' failed to load. If you know, please tell me how to solve it.Thank you very much.

**Comment by VamosCC** [comment]
> How did you solve the first problem?The plugin for class 'rviz_plugins/Goal3DTool' failed to load. If you know, please tell me how to solve it.Thank you very much.

After 'catkin_make' the pkgs, which include rviz_plugins with Goal3DTool, You should excute '**source devel/setup.sh**', then rviz can locate to current project defined rviz_plugins with Goal3DTool, and the question solved.
