### ISSUE TITLE
trr_simulation related issue

### ISSUE THREAD

**Issue by LTianyyi** [HKUST-Aerial-Robotics/Teach-Repeat-Replan#41]
I use keyboard and when I run ./trr_simulation.sh, there are some errors about joy_node.
I think the second line at ./trr_simulation.sh
`rosrun joy joy_node & sleep 0.2;`
should be change to 
`python key2joy.py & sleep 0.2;`
Is that right? Thank you and your team for this brilliant work.

**Comment by bigsuperZZZX** [comment]
That's right. `rosrun joy joy_node` is for XBOX joystick and you can replace it by keyboard using `python key2joy.py`.

**Comment by LTianyyi** [comment]
Thanks for your help!
