### ISSUE TITLE
Path planning in actual flight

### ISSUE THREAD

**Issue by G1246830895** [HKUST-Aerial-Robotics/Teach-Repeat-Replan#44]
We successfully planned an executable path, but when we generate the optimized path with teaching_planning.sh, the optimized path always starts from the origin of the coordinate system. We use the remote control to control the aircraft correctly, but the aircraft does not execute the path we planned and prints "[ INFO] [1595826566.979165352]: Integration saturate for axis 1, value=0.400". We watched your operation video and found that your drone was in flight during the teach phase, and our situation would not happen. How did you do it?

**Comment by G1246830895** [comment]
![image](https://user-images.githubusercontent.com/48216024/88510340-5ceabe00-d015-11ea-890d-bd272fcf9e2e.png)
![image](https://user-images.githubusercontent.com/48216024/88510393-7986f600-d015-11ea-940f-21968af8ced6.png)

**Comment by USTfgaoaa** [comment]
@G1246830895 Of course you shoudl launch the drone and trigger the trajectory generation. There is no auto-take off functionality.

**Comment by G1246830895** [comment]
Yes, we did. The path we plan always starts from the origin of the coordinates, not in the air. So after we take off the drone, the drone will not execute the planned path

**Comment by USTfgaoaa** [comment]
@G1246830895 The traj generated "always must" starts from the current state of the drone, not any coordinate no matter the origin or the air. Please make sure you correctly set all params/topics and figure out the system msgs flow.

**Comment by G1246830895** [comment]
![image](https://user-images.githubusercontent.com/48216024/88515281-0930a280-d01e-11ea-9ec1-f0ad7a8fd650.png)
The path we planned is like this
