### ISSUE TITLE
Fix dependency problem.

### ISSUE THREAD

**Issue by ZhepeiWang** [HKUST-Aerial-Robotics/Teach-Repeat-Replan#45]
target_link_libraries(poly_utils ${catkin_LIBRARIES})

It should be added to the line 42 at https://github.com/HKUST-Aerial-Robotics/Teach-Repeat-Replan/blob/master/global_planner/CMakeLists.txt.

**Comment by bigsuperZZZX** [comment]
:thumbsup::thumbsup::thumbsup:
