### ISSUE TITLE
Cannot find a safe solution

### ISSUE THREAD

**Issue by itsalpha** [HKUST-Aerial-Robotics/Teach-Repeat-Replan#46]
Hello, I have always liked your work very much, but when I went to retest, the following questions appeared, I would like to ask you to help answer them.
1.
![Screenshot from 2020-11-12 04-46-01](https://user-images.githubusercontent.com/55071916/98863314-255c3080-24a3-11eb-8ea0-77c85f7a9ca0.png)
2.
![Screenshot from 2020-11-12 04-46-23](https://user-images.githubusercontent.com/55071916/98863352-3016c580-24a3-11eb-8239-aa5808a1ef3b.png)
Thank you very much!

**Comment by itsalpha** [comment]
I didn't have flight control and camera drive on the ground station.will it matter?

**Comment by bigsuperZZZX** [comment]
I have no idea about the exact problem with the given figures.
The first figure is some plugin errors related to rviz, which does not matter.
I suggest you start testing from a simple teaching trajectory that contains as fewer polyhedrons as possible, then check that there is no disconnection(break) between adjacent polyhedrons from rviz.
In addition, make sure that the drone is inside one polyhedron once you press the start button.
Flight control and camera drive will not affect the global planner.

**Comment by itsalpha** [comment]
Thank you very much for your reply. I am testing the model-balcony I brought in the project now, but I can not solve an optimized path by modifying the resolution and map size. There is also in the global-planner-exp.launch file trr-global-planner node file-path need to be set?

**Comment by itsalpha** [comment]
![Screenshot from 2020-11-12 11-43-02](https://user-images.githubusercontent.com/55071916/98892946-6290e480-24dc-11eb-9524-64044851078f.png)

**Comment by bigsuperZZZX** [comment]
Try a teaching path like this
![image](https://user-images.githubusercontent.com/26641182/98894074-f1066580-24de-11eb-83b9-6ba8296764fe.png)

**Comment by itsalpha** [comment]
@bigsuperZZZX 
![Screenshot from 2020-11-12 12-13-46](https://user-images.githubusercontent.com/55071916/98894795-92da8200-24e0-11eb-97bc-950e871d7927.png)
not ok.

**Comment by USTfgaoaa** [comment]
@itsalpha pilot the drone to go around an obstacle and back. Try it again.

**Comment by itsalpha** [comment]
@USTfgaoaa sorry,my dear teacher,it still doesn't work.But it can be run in simulation.
![Screenshot from 2020-11-12 13-28-03](https://user-images.githubusercontent.com/55071916/98899780-4779a100-24eb-11eb-8fe1-3cb65316616a.png)

**Comment by USTfgaoaa** [comment]
@itsalpha So you are going to conduct real-world experiments? Make sure you know how this system functions. For example, for real flight here the odometry name in the launch file should be the topic name of your onboard estimated pose.

**Comment by itsalpha** [comment]
@bigsuperZZZX I'm sorry to brother you again,after i modified the launch file,i will see the generated track ,but the effect id not good,is this the reason why the launch file is not configured correctly?
![Screenshot from 2020-11-12 23-18-32](https://user-images.githubusercontent.com/55071916/98959545-58073700-253e-11eb-9d6b-e28ceacb4a8e.png)
1.gobal_planner.luanch
```c
<launch>

<arg name="map_size_x" default="20.0"/>
<arg name="map_size_y" default="20.0"/>
<arg name="map_size_z" default="5.0"/>

<arg name="init_x" default="0.0"/>
<arg name="init_y" default="0.0"/>
<arg name="init_z" default="1.0"/>

<arg name="max_vel" default="0.4"/>
<arg name="max_acc" default="0.8"/>

<arg name="resolution" default="0.33"/>
<arg name="poly_order" default="5"/>

  <node pkg="trr_global_planner" type="tr_node" name="tr_node" output="screen" required = "true">
      <remap from="~odometry"    to="/drone_1/visual_slam/odom"    />
      <remap from="~map"         to="/cloud_pcd"   /> 
      <remap from="~joystick"    to="/joy"/> 
      <remap from="~trigger"     to="/time_optimal_traj_server/start_pose"/>

      <param name="write_path"  value="false" /> 
      <param name="read_path"   value="false" /> 

      <param name="optimization/poly_order"  value="$(arg poly_order)"     /> 
      <param name="optimization/min_order"   value="3.0"   /> 
      
      <param name="map/x_size"       value="$(arg map_size_x)"/>
      <param name="map/y_size"       value="$(arg map_size_y)"/>
      <param name="map/z_size"       value="$(arg map_size_z)"/>
      
      <param name="map/map_margin"   value="0.1" />
      <param name="map/resolution"   value="$(arg resolution)" />
      
      <param name="planning/rho_time"      value="10.0"/>
      <param name="planning/max_vel"       value="$(arg max_vel)" />
      <param name="planning/max_acc"       value="$(arg max_acc)" />
      <param name="planning/max_d_acc"     value="1.0" />
      <param name="planning/max_inf_iter"  value="10"  />
      <param name="planning/max_clu_iter"  value="5"  />

      <param name="z_cost_weight"  value="100.0"  />

      <param name="vis/vis_traj_width"     value="0.1  "/>
      <param name="your_file_path"         value="/home/zx/TRR_ws/catkin_ws/path_pts"/>
  </node>
</launch>
```
2.joy_ctrl.launch
```c
<?xml version="1.0"?>

<launch>
  <node pkg="joy_ctrl" type="joy_ctrl" name="joy_ctrl_sim" output="screen">
    <remap from="~joy" to="/joy"/>
    <remap from="~uav_odom_sim" to="/drone_1/visual_slam/odom"/>
    <param name="start_x"   type="double" value=" 0.0"/>
    <param name="start_y"   type="double" value=" 0.0"/>
    <param name="start_z"   type="double" value=" 1.0"/>
    <param name="start_yaw" type="double" value="0.0"/>

    <param name="min_z"   type="double" value=" 0.0"/>
    <param name="max_z"   type="double" value=" 2.0"/>


    <param name="hori_scale" type="double" value="0.03"/>
    <param name="vert_scale" type="double" value="0.02"/>
    <param name="yaw_scale"  type="double" value="0.01"/>
  
  </node>

<!-- Visualization-->
<!--node pkg="odom_visualization" name="odom_visualization" type="odom_visualization" output="screen">
  <remap from="~odom"            to="/uav_odom_sim"/>
  <param name="base_frame"       value="/world"/>
  <param name="color/a"          value="1.0"/>
  <param name="color/r"          value="0.0"/>
  <param name="color/g"          value="0.0"/>
  <param name="color/b"          value="0.0"/>
  <param name="robot_scale"      value="1.0"/>
</node-->

<node pkg="odom_visualization"
      name="odom_visualization_1"
      type="odom_visualization"
      output="log">
  <remap from="~odom"            to="/drone_1/visual_slam/odom"/>
  <remap from="~odom_world"      to="/all_odom"/>
  <param name="base_frame"       value="/map"/>
  <param name="target_frame"     value="/map"/>
  <param name="tf45"             value="true"/>
  <param name="tfc"              value="false"/>
  <param name="color/a"          value="1.0"/>
  <param name="color/r"          value="1.0"/>
  <param name="color/g"          value="0.0"/>
  <param name="color/b"          value="0.0"/>
  <param name="covariance_scale" value="100.0"/>
  <param name="drone_scale"      value="0.8"/>
  <param name="id"      value="1"/>
</node>

 <node name="rviz" pkg="rviz" type="rviz" output="log"
       args="-d $(find trr_global_planner)/config/rviz_config.rviz"> 
</node>

</launch>
```
3.rostopic list
```c
/camera/depth/camera_info
/camera/depth/image_rect_raw
/camera/extrinsics/depth_to_infra1
/camera/extrinsics/depth_to_infra2
/camera/imu
/camera/imu_info
/camera/infra1/camera_info
/camera/infra1/image_rect_raw
/camera/infra2/camera_info
/camera/infra2/image_rect_raw
/camera/motion_module/parameter_descriptions
/camera/motion_module/parameter_updates
/camera/realsense2_camera_manager/bond
/camera/rgb_camera/parameter_descriptions
/camera/rgb_camera/parameter_updates
/camera/stereo_module/parameter_descriptions
/camera/stereo_module/parameter_updates
/desire_pose
/diagnostics
/djiros/ctrl
/djiros/display_mode
/djiros/flight_status
/djiros/from_mobile_data
/djiros/gimbal_angle
/djiros/gps
/djiros/gps_health
/djiros/imu
/djiros/rc
/djiros/velo
/drone_1/visual_slam/odom
/feature_tracker/feature
/joy
/keyboard/twist
/local_replanner/boundary_acc_vis
/local_replanner/boundary_vel_vis
/local_replanner/bspline
/local_replanner/check_trajectory_vis
/local_replanner/fill_esdf_vis
/local_replanner/initial_b_spline_vis
/local_replanner/replaned_b_spline_vis
/loop_fusion/base_path
/loop_fusion/camera_pose_visual
/loop_fusion/margin_cloud_loop_rect
/loop_fusion/match_image
/loop_fusion/odometry_rect
/loop_fusion/path_1
/loop_fusion/path_2
/loop_fusion/path_3
/loop_fusion/path_4
/loop_fusion/path_5
/loop_fusion/path_6
/loop_fusion/path_7
/loop_fusion/path_8
/loop_fusion/path_9
/loop_fusion/pg_T_vio
/loop_fusion/point_cloud_loop_rect
/loop_fusion/pose_graph
/loop_fusion/pose_graph_path
/n3ctrl/ctrl_dbg/a
/n3ctrl/ctrl_dbg/att_des
/n3ctrl/ctrl_dbg/att_real
/n3ctrl/ctrl_dbg/info
/n3ctrl/ctrl_dbg/p
/n3ctrl/ctrl_dbg/v
/n3ctrl/ctrl_dbg/value
/n3ctrl/ctrl_so3/attitude
/n3ctrl/ctrl_so3/thrust
/n3ctrl/ctrl_vis
/n3ctrl/enter_js
/n3ctrl/fsm_dbg
/n3ctrl/hov_thr
/n3ctrl/idling
/n3ctrl/state_led
/pcl_render_node/local_pointcloud
/position_cmd
/rosout
/rosout_agg
/sdf_map/esdf
/sdf_map/occupancy
/sdf_map/occupancy_inflate
/sdf_map/test
/sdf_map/update_range
/tf
/tf_static
/time_optimal_traj_server/check_pts
/time_optimal_traj_server/current_pose
/time_optimal_traj_server/desired_acceleration
/time_optimal_traj_server/desired_position
/time_optimal_traj_server/desired_velocity
/time_optimal_traj_server/start_pose
/time_optimal_traj_server/vis_yaw_cmd
/tr_node/space_time_traj
/traj_start_trigger
/view
/vins_estimator/camera_pose
/vins_estimator/camera_pose_visual
/vins_estimator/extrinsic
/vins_estimator/imu_propagate
/vins_estimator/key_poses
/vins_estimator/keyframe_point
/vins_estimator/keyframe_pose
/vins_estimator/margin_cloud
/vins_estimator/odometry
/vins_estimator/path
/vins_estimator/point_cloud

```

**Comment by xyft123** [comment]
> @bigsuperZZZX I'm sorry to brother you again,after i modified the launch file,i will see the generated track ,but the effect id not good,is this the reason why the launch file is not configured correctly?
> ![Screenshot from 2020-11-12 23-18-32](https://user-images.githubusercontent.com/55071916/98959545-58073700-253e-11eb-9d6b-e28ceacb4a8e.png)
> 1.gobal_planner.luanch
> 
> ```c
> <launch>
> 
> <arg name="map_size_x" default="20.0"/>
> <arg name="map_size_y" default="20.0"/>
> <arg name="map_size_z" default="5.0"/>
> 
> <arg name="init_x" default="0.0"/>
> <arg name="init_y" default="0.0"/>
> <arg name="init_z" default="1.0"/>
> 
> <arg name="max_vel" default="0.4"/>
> <arg name="max_acc" default="0.8"/>
> 
> <arg name="resolution" default="0.33"/>
> <arg name="poly_order" default="5"/>
> 
>   <node pkg="trr_global_planner" type="tr_node" name="tr_node" output="screen" required = "true">
>       <remap from="~odometry"    to="/drone_1/visual_slam/odom"    />
>       <remap from="~map"         to="/cloud_pcd"   /> 
>       <remap from="~joystick"    to="/joy"/> 
>       <remap from="~trigger"     to="/time_optimal_traj_server/start_pose"/>
> 
>       <param name="write_path"  value="false" /> 
>       <param name="read_path"   value="false" /> 
> 
>       <param name="optimization/poly_order"  value="$(arg poly_order)"     /> 
>       <param name="optimization/min_order"   value="3.0"   /> 
>       
>       <param name="map/x_size"       value="$(arg map_size_x)"/>
>       <param name="map/y_size"       value="$(arg map_size_y)"/>
>       <param name="map/z_size"       value="$(arg map_size_z)"/>
>       
>       <param name="map/map_margin"   value="0.1" />
>       <param name="map/resolution"   value="$(arg resolution)" />
>       
>       <param name="planning/rho_time"      value="10.0"/>
>       <param name="planning/max_vel"       value="$(arg max_vel)" />
>       <param name="planning/max_acc"       value="$(arg max_acc)" />
>       <param name="planning/max_d_acc"     value="1.0" />
>       <param name="planning/max_inf_iter"  value="10"  />
>       <param name="planning/max_clu_iter"  value="5"  />
> 
>       <param name="z_cost_weight"  value="100.0"  />
> 
>       <param name="vis/vis_traj_width"     value="0.1  "/>
>       <param name="your_file_path"         value="/home/zx/TRR_ws/catkin_ws/path_pts"/>
>   </node>
> </launch>
> ```
> 
> 2.joy_ctrl.launch
> 
> ```c
> <?xml version="1.0"?>
> 
> <launch>
>   <node pkg="joy_ctrl" type="joy_ctrl" name="joy_ctrl_sim" output="screen">
>     <remap from="~joy" to="/joy"/>
>     <remap from="~uav_odom_sim" to="/drone_1/visual_slam/odom"/>
>     <param name="start_x"   type="double" value=" 0.0"/>
>     <param name="start_y"   type="double" value=" 0.0"/>
>     <param name="start_z"   type="double" value=" 1.0"/>
>     <param name="start_yaw" type="double" value="0.0"/>
> 
>     <param name="min_z"   type="double" value=" 0.0"/>
>     <param name="max_z"   type="double" value=" 2.0"/>
> 
> 
>     <param name="hori_scale" type="double" value="0.03"/>
>     <param name="vert_scale" type="double" value="0.02"/>
>     <param name="yaw_scale"  type="double" value="0.01"/>
>   
>   </node>
> 
> 
> 
> 
> <node pkg="odom_visualization"
>       name="odom_visualization_1"
>       type="odom_visualization"
>       output="log">
>   <remap from="~odom"            to="/drone_1/visual_slam/odom"/>
>   <remap from="~odom_world"      to="/all_odom"/>
>   <param name="base_frame"       value="/map"/>
>   <param name="target_frame"     value="/map"/>
>   <param name="tf45"             value="true"/>
>   <param name="tfc"              value="false"/>
>   <param name="color/a"          value="1.0"/>
>   <param name="color/r"          value="1.0"/>
>   <param name="color/g"          value="0.0"/>
>   <param name="color/b"          value="0.0"/>
>   <param name="covariance_scale" value="100.0"/>
>   <param name="drone_scale"      value="0.8"/>
>   <param name="id"      value="1"/>
> </node>
> 
>  <node name="rviz" pkg="rviz" type="rviz" output="log"
>        args="-d $(find trr_global_planner)/config/rviz_config.rviz"> 
> </node>
> 
> </launch>
> ```
> 
> 3.rostopic list
> 
> ```c
> /camera/depth/camera_info
> /camera/depth/image_rect_raw
> /camera/extrinsics/depth_to_infra1
> /camera/extrinsics/depth_to_infra2
> /camera/imu
> /camera/imu_info
> /camera/infra1/camera_info
> /camera/infra1/image_rect_raw
> /camera/infra2/camera_info
> /camera/infra2/image_rect_raw
> /camera/motion_module/parameter_descriptions
> /camera/motion_module/parameter_updates
> /camera/realsense2_camera_manager/bond
> /camera/rgb_camera/parameter_descriptions
> /camera/rgb_camera/parameter_updates
> /camera/stereo_module/parameter_descriptions
> /camera/stereo_module/parameter_updates
> /desire_pose
> /diagnostics
> /djiros/ctrl
> /djiros/display_mode
> /djiros/flight_status
> /djiros/from_mobile_data
> /djiros/gimbal_angle
> /djiros/gps
> /djiros/gps_health
> /djiros/imu
> /djiros/rc
> /djiros/velo
> /drone_1/visual_slam/odom
> /feature_tracker/feature
> /joy
> /keyboard/twist
> /local_replanner/boundary_acc_vis
> /local_replanner/boundary_vel_vis
> /local_replanner/bspline
> /local_replanner/check_trajectory_vis
> /local_replanner/fill_esdf_vis
> /local_replanner/initial_b_spline_vis
> /local_replanner/replaned_b_spline_vis
> /loop_fusion/base_path
> /loop_fusion/camera_pose_visual
> /loop_fusion/margin_cloud_loop_rect
> /loop_fusion/match_image
> /loop_fusion/odometry_rect
> /loop_fusion/path_1
> /loop_fusion/path_2
> /loop_fusion/path_3
> /loop_fusion/path_4
> /loop_fusion/path_5
> /loop_fusion/path_6
> /loop_fusion/path_7
> /loop_fusion/path_8
> /loop_fusion/path_9
> /loop_fusion/pg_T_vio
> /loop_fusion/point_cloud_loop_rect
> /loop_fusion/pose_graph
> /loop_fusion/pose_graph_path
> /n3ctrl/ctrl_dbg/a
> /n3ctrl/ctrl_dbg/att_des
> /n3ctrl/ctrl_dbg/att_real
> /n3ctrl/ctrl_dbg/info
> /n3ctrl/ctrl_dbg/p
> /n3ctrl/ctrl_dbg/v
> /n3ctrl/ctrl_dbg/value
> /n3ctrl/ctrl_so3/attitude
> /n3ctrl/ctrl_so3/thrust
> /n3ctrl/ctrl_vis
> /n3ctrl/enter_js
> /n3ctrl/fsm_dbg
> /n3ctrl/hov_thr
> /n3ctrl/idling
> /n3ctrl/state_led
> /pcl_render_node/local_pointcloud
> /position_cmd
> /rosout
> /rosout_agg
> /sdf_map/esdf
> /sdf_map/occupancy
> /sdf_map/occupancy_inflate
> /sdf_map/test
> /sdf_map/update_range
> /tf
> /tf_static
> /time_optimal_traj_server/check_pts
> /time_optimal_traj_server/current_pose
> /time_optimal_traj_server/desired_acceleration
> /time_optimal_traj_server/desired_position
> /time_optimal_traj_server/desired_velocity
> /time_optimal_traj_server/start_pose
> /time_optimal_traj_server/vis_yaw_cmd
> /tr_node/space_time_traj
> /traj_start_trigger
> /view
> /vins_estimator/camera_pose
> /vins_estimator/camera_pose_visual
> /vins_estimator/extrinsic
> /vins_estimator/imu_propagate
> /vins_estimator/key_poses
> /vins_estimator/keyframe_point
> /vins_estimator/keyframe_pose
> /vins_estimator/margin_cloud
> /vins_estimator/odometry
> /vins_estimator/path
> /vins_estimator/point_cloud
> ```

I've met the same problem, how did you finally solve it?
