### ISSUE TITLE
Ubuntu18.04 compile OOQP Error.

### ISSUE THREAD

**Issue by Yunhui-LI** [HKUST-Aerial-Robotics/Teach-Repeat-Replan#47]
src/Readers/hash.C: In function ‘int Insert(HashTable*, char*, int)’:
src/Readers/hash.C:163:7: error: reference to ‘hash’ is ambiguous
   i = hash(table, name);

![Screenshot from 2021-05-27 16-45-21](https://user-images.githubusercontent.com/37470006/119795553-2a4a7400-bf0b-11eb-8771-6339e9061bf9.png)

**Comment by leo-wkd** [comment]
I also encountered this problem. You could change gcc and g++ version to 5 and reinstall the boost library to solve this issue.

**Comment by bigsuperZZZX** [comment]
:thumbsup::thumbsup::thumbsup:

**Comment by saumonk** [comment]
We can avoid this by removing the line using namespace std, and replacing cerr to std::cerr.
