### ISSUE TITLE
What dynamical system do you use? Could you give me a purchase list.

### ISSUE THREAD

**Issue by Admire-ljb** [HKUST-Aerial-Robotics/Teach-Repeat-Replan#49]
Hello, 
      I would like to repeat your research, could you please provide your hardware list? I saw only the control part in the paper, could you also provide the frame and power system? Thank you.

**Comment by bigsuperZZZX** [comment]
Well, any FPV power system is OK. Just don't be too cheap.
We use a Q250 airframe, and the motors and ESCs are from T-motor. 
You can also buy a finished FPV drone.

**Comment by Admire-ljb** [comment]
Thanks a lot！
