### ISSUE TITLE
Can not pilot the drone using my keyboard and errors occured when the system is launched by ./trr_simulation.sh

### ISSUE THREAD

**Issue by KangchengLiu** [HKUST-Aerial-Robotics/Teach-Repeat-Replan#5]
Hi, Gaofei and Boyu,
Nice project and I like this Teach-Repeat-Replan.
Now I followed your advices and install the packages and the package can be launched. But I can't pilot the drone using my keyboard. And some errors occured and I have no idea how to deal with them.
![rviz](https://user-images.githubusercontent.com/37166840/61991514-b5465300-b083-11e9-8eed-7c38763d1bf7.png)
1. The joystick force feedback can not be opened.
![error_1](https://user-images.githubusercontent.com/37166840/61991507-95169400-b083-11e9-9536-5bc96e5502af.png)
2. 2 processes have died.
![error_2](https://user-images.githubusercontent.com/37166840/61991513-a364b000-b083-11e9-9a96-e1428299e1ad.png)
![error_3](https://user-images.githubusercontent.com/37166840/61991511-9b0c7500-b083-11e9-8fa3-139395602f15.png)
 I will appreciate if you can help me, thanks!

**Comment by USTfgaoaa** [comment]
@KangchengLiu 
Hi, I haven't encountered problems with joystick before, but I will try to help you fix it.
May you comment this line 'rosrun joy joy_node & sleep 0.2;' in the trr_simulation script, and try launch it again to see whether the process die?

**Comment by USTfgaoaa** [comment]
@KangchengLiu 
Do you connect a joystick to your computer?

**Comment by KangchengLiu** [comment]
It finally turned out that the process died because the sleep time between roslaunch trr_global_planner and roslaunch trr_global_planner was too short that my laptop can not deal with it.

You can fix it by doing roslaunch one by one or increase the sleep time in the trr_simulation script.

Thanks Gao Fei for his kind help!
