### ISSUE TITLE
global planner can't work

### ISSUE THREAD

**Issue by pang0224** [HKUST-Aerial-Robotics/Teach-Repeat-Replan#51]
感谢您开源代码的分享！
我在室外环境下进行地图构建，但是同样环境的两个地图下，一个可以成功规划，另一个却不能，我不知道出现了什么问题。
在可以成功规划的地图上，resolution在0.1及以下可以成功规划，高了则不行。

![4](https://user-images.githubusercontent.com/84223753/134798874-2595b33a-5e33-4de8-8e77-e8e8aaf6db07.png)

在无法成功规划的地图上中，我的示教轨迹和报错信息如下：
![1](https://user-images.githubusercontent.com/84223753/134798300-fb85bf76-ae61-4d99-bdde-f898a061521e.png)

![2](https://user-images.githubusercontent.com/84223753/134798315-49799f13-51b5-4775-928e-12523ab2e1c4.png)

我尝试了修改地图大小和更改resolution，在resolution为0.01的情况下仍不能成功规划，resolution在0.3以上的情况下也不能成功，我也调整了地图大小，把他改的足够大，但仍然不行。
![3](https://user-images.githubusercontent.com/84223753/134798666-fb5d8c0e-c6e6-4d03-9980-657d7b38ba4a.png)

您有什么好的建议吗？
另外我还有两个小问题，希望您能帮忙解答
1、在global_planner_exp.launch中的init_x,y,z参数好像没有在地图上体现，这三个参数有什么用呢？
2、在无人机执行规划路径时，可以先进行示教，再让无人机起飞悬停，最后按m键触发规划并切换模式吗？我注意到规划开始的起点在坐标原点，不知道会对规划轨迹的执行产生什么样的结果，您使用的正确顺序是什么样的呢？
期待您的答复，万分感谢！

**Comment by bigsuperZZZX** [comment]
非常抱歉这么久才回，近期实在是忙碌。
1. 关于规划失败的原因，可能参考[这个issue](https://github.com/HKUST-Aerial-Robotics/Teach-Repeat-Replan/issues/31)会有些帮助，如果还是不行，请在这边继续提问。
2. init_x,y,z这三个参数我检查了一下，确实是没用的。
3. 如果规划的开始点不在原点，那其实是说明你的odometry没有正确的接入，当odometry正确接入以后规划的起始点应该是飞机当前odometry的所在点。正确的顺序是先仿真中遥控飞一遍，然后起飞飞机切换到悬停随后切到自动待命，然后按m键触发规划，规划成功后飞机就会沿着轨迹飞了

**Comment by pang0224** [comment]
好的，非常感谢您的回复
