### ISSUE TITLE
controller的使用

### ISSUE THREAD

**Issue by hanlei666-python** [HKUST-Aerial-Robotics/Teach-Repeat-Replan#52]
你好，我想在TX2上使用T265相机输出的视觉里程计信息作为实际位置信息，用于N3飞控室内飞行。也就是说我仅仅想利用n3ctrl模块和djiros模块。我想将实际位置信息和期望位置信息作为controller的输入，然后输出期望姿态信息并交给N3飞控。
    请问我需要作什么改动？以及我自己的程序需要向这些模块发送哪些rostopic信息？另外，能否提供上诉模块之间rostopic的graph？ 
    非常感谢您的工作！万分希望您能为我解答！

**Comment by bigsuperZZZX** [comment]
现在搞个graph还真不好搞，不过这俩节点用起来很简单。
djiros只要安装好、正常启动（roslaunch djiros djiros.launch）即可，n3ctrl会负责与它的通信，不需要用户介入。
n3ctrl接收两个主要的用户topic，分别是一个odometry和一个控制指令，然后就能用了。更多细节看它的[readme](https://github.com/HKUST-Aerial-Robotics/Teach-Repeat-Replan/tree/experiment/onboard_computer/controller/n3ctrl)即可

**Comment by bigsuperZZZX** [comment]
没啥别的问题的话我就关了
