### ISSUE TITLE
Some questions about controller

### ISSUE THREAD

**Issue by dssdyx** [HKUST-Aerial-Robotics/Teach-Repeat-Replan#53]
I know you use se3 controller to compute desired angels from desired pva, but there are two questions in code confusing me.
1. In controller.cpp line 241~217, why using Z-Y-X rotation sequence but not Z-X-Y rotation sequence? Because of FRD frame? How to know rotation sequence in other coordinates?
2. In controller.cpp line 257~258,why using Fc to express desired roll and pitch but not R_des?

**Comment by bigsuperZZZX** [comment]
1. Z-Y-X rotation sequence makes the drone heading which is also the camera's z-direction precisely point to the yaw angle we gave when they all projected onto the x-y plane in the world frame.
2. Please refer to [this function](https://github.com/HKUST-Aerial-Robotics/Teach-Repeat-Replan/blob/949bc1b2b3db1486729f32d3ba73fbca863fecac/onboard_computer/controller/n3ctrl/src/controller.cpp#L297) to see how N3 FCU receives commands from the controller. The commands mimic human control using an RC in attitude mode (the stabilized mode in PX4) which is just in the FRD frame.

**Comment by dssdyx** [comment]
> 1. Z-Y-X rotation sequence makes the drone heading which is also the camera's z-direction precisely point to the yaw angle we gave when they all projected onto the x-y plane in the world frame.
> 2. Please refer to [this function](https://github.com/HKUST-Aerial-Robotics/Teach-Repeat-Replan/blob/949bc1b2b3db1486729f32d3ba73fbca863fecac/onboard_computer/controller/n3ctrl/src/controller.cpp#L297) to see how N3 FCU receives commands from the controller. The commands mimic human control using an RC in attitude mode (the stabilized mode in PX4) which is just in the FRD frame.

2. I know that N3 uses FRD frame, but my question is when you compute the desired ypr, [the code](https://github.com/HKUST-Aerial-Robotics/Teach-Repeat-Replan/blob/949bc1b2b3db1486729f32d3ba73fbca863fecac/onboard_computer/controller/n3ctrl/src/controller.cpp#L257-L258) ignores desired R but uses F_c which is projection of F_des in c-coordinate to express roll and pitch. In SE3 controller, desired R can be directly transformed into desired ypr, so I don't understand why F_des's projection can be used here.

**Comment by bigsuperZZZX** [comment]
Maybe I still haven't got it, do you mean why we use F_c to compute ypr instead of using R?
They make no difference, which to use just depends on which one came to head first when writing the code.

**Comment by dssdyx** [comment]
> Maybe I still haven't got it, do you mean why we use F_c to compute ypr instead of using R? They make no difference, which to use just depends on which one came to head first when writing the code.

Thank you.I understand. You mean using F_c or R is same in math and geometric which just different in expression.

**Comment by bigsuperZZZX** [comment]
That's true.
