### ISSUE TITLE
Question about referent localization

### ISSUE THREAD

**Issue by dssdyx** [HKUST-Aerial-Robotics/Teach-Repeat-Replan#58]
Hi, I want to use n3ctrl controller in real-world experiment, but the FCU I use is px4. Now, I feel confused about referent localization. I use onboard VINS and transform its localization data as vision pose to px4. You know px4 will output a merged localization with vision pose and its imu data from EKF2. I don't know use which one to input planner and controller. When I use raw VINS data, its frequency is only 15hz, I think it's a little low for controller. When I use FCU merged data, its frequency is enough, but it seems have a little drift compared with raw VINS data. Do you have good idea about which one is better in this situation?Thank you very much!

**Comment by bigsuperZZZX** [comment]
Using the /vins_estimator/imu_propagate topic.

**Comment by dssdyx** [comment]
> Using the /vins_estimator/imu_propagate topic.

Thank you for your answer! Very helpful!
