### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by kukulinxin** [HKUST-Aerial-Robotics/Teach-Repeat-Replan#65]
在编译是发现报错如下，不懂原因是什么，eigen3.3.9和eigen3.3.7都试过了：
![2023-05-11 13-22-57 的屏幕截图](https://github.com/HKUST-Aerial-Robotics/Teach-Repeat-Replan/assets/114294307/df8ee9c9-54ae-418c-acb4-e33a86ea00f7)

**Comment by bigsuperZZZX** [comment]
多个Eigen版本整乱了吧，Eigen自己的库里的文件之间互相冲突

**Comment by kukulinxin** [comment]
因为之前跑不同的代码，环境里面确实有几个版本的eigen库，但是我是进行管理的，就是在usr/include下我有几个不同的版本的eigen库文件夹，想用哪个的时候就把想用的版本的eigen库文件夹名字改为eigen3，然后再把usr/share/configpkg里的eigen3.pc
里面也修改一下。这个方法我也是参考网上的，应该没什么问题吧。

**Comment by bigsuperZZZX** [comment]
这样做是否能够与比如EGO-Planner这种第三方软件兼容，我也说不好了

**Comment by kukulinxin** [comment]
> 这样做是否能够与比如EGO-Planner这种第三方软件兼容，我也说不好了

好的，感谢。
